// Automatically generated by MockGen. DO NOT EDIT!
// Source: registry.go

package event

import (
	gomock "github.com/dsymonds/gomock/gomock"
)

// Mock of Handler interface
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *_MockHandlerRecorder
}

// Recorder for MockHandler (not exported)
type _MockHandlerRecorder struct {
	mock *MockHandler
}

func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &_MockHandlerRecorder{mock}
	return mock
}

func (_m *MockHandler) EXPECT() *_MockHandlerRecorder {
	return _m.recorder
}

func (_m *MockHandler) Run(_param0 ...interface{}) {
	_m.ctrl.Call(_m, "Run", _param0)
}

func (_mr *_MockHandlerRecorder) Run(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run", arg0)
}

func (_m *MockHandler) Id() HandlerID {
	ret := _m.ctrl.Call(_m, "Id")
	ret0, _ := ret[0].(HandlerID)
	return ret0
}

func (_mr *_MockHandlerRecorder) Id() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Id")
}

// Mock of EventDispatcher interface
type MockEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *_MockEventDispatcherRecorder
}

// Recorder for MockEventDispatcher (not exported)
type _MockEventDispatcherRecorder struct {
	mock *MockEventDispatcher
}

func NewMockEventDispatcher(ctrl *gomock.Controller) *MockEventDispatcher {
	mock := &MockEventDispatcher{ctrl: ctrl}
	mock.recorder = &_MockEventDispatcherRecorder{mock}
	return mock
}

func (_m *MockEventDispatcher) EXPECT() *_MockEventDispatcherRecorder {
	return _m.recorder
}

func (_m *MockEventDispatcher) Dispatch(name string, ev ...interface{}) {
	_m.ctrl.Call(_m, "Dispatch", name, ev)
}

func (_mr *_MockEventDispatcherRecorder) Dispatch(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Dispatch", arg0, arg1)
}

// Mock of EventRegistry interface
type MockEventRegistry struct {
	ctrl     *gomock.Controller
	recorder *_MockEventRegistryRecorder
}

// Recorder for MockEventRegistry (not exported)
type _MockEventRegistryRecorder struct {
	mock *MockEventRegistry
}

func NewMockEventRegistry(ctrl *gomock.Controller) *MockEventRegistry {
	mock := &MockEventRegistry{ctrl: ctrl}
	mock.recorder = &_MockEventRegistryRecorder{mock}
	return mock
}

func (_m *MockEventRegistry) EXPECT() *_MockEventRegistryRecorder {
	return _m.recorder
}

func (_m *MockEventRegistry) AddHandler(h Handler, names ...string) {
	_m.ctrl.Call(_m, "AddHandler", h, names)
}

func (_mr *_MockEventRegistryRecorder) AddHandler(arg0 interface{}, arg1 ...string) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddHandler", arg0, arg1)
}

func (_m *MockEventRegistry) DelHandler(h Handler, names ...string) {
	_m.ctrl.Call(_m, "DelHandler", h, names)
}

func (_mr *_MockEventRegistryRecorder) DelHandler(arg0 interface{}, arg1 ...string) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DelHandler", arg0, arg1)
}

func (_m *MockEventRegistry) Dispatch(name string, ev ...interface{}) {
	_m.ctrl.Call(_m, "Dispatch", name, ev)
}

func (_mr *_MockEventRegistryRecorder) Dispatch(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Dispatch", arg0, arg1)
}

func (_m *MockEventRegistry) ClearEvents(name string) {
	_m.ctrl.Call(_m, "ClearEvents", name)
}

func (_mr *_MockEventRegistryRecorder) ClearEvents(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ClearEvents", arg0)
}
